// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qiymydnhymiyqsxnxieu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpeW15ZG5oeW1peXFzeG54aWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzA1OTksImV4cCI6MjA2OTgwNjU5OX0.0j_GQYY9ixOWV0INUtBJpyNAibi_QIOsZ2Uku2Nw-ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});